mybatis:
 type-aliases-package: com.neo.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver