mybatis:
 type-aliases-package: com.neo.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss:SSS,GMT+8} - %5p ${PID:- } --- [%15.15t] %-40.40logger{39} :%3L: %m%n:-%wEx"
